reference: https://zhuanlan.zhihu.com/p/101799677

In [4]:
import torch
torch.__version__

'1.6.0'

In [5]:
from __future__ import print_function
import torch

In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[7.1633e-39, 1.0469e-38, 1.0194e-38],
        [4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39]])


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0870, 0.0188, 0.6805],
        [0.7064, 0.8285, 0.7161],
        [0.7744, 0.8644, 0.8783],
        [0.4227, 0.6991, 0.7261],
        [0.1692, 0.3371, 0.3309]])


In [8]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])
