reference: https://zhuanlan.zhihu.com/p/101799677

In [13]:
import torch
torch.__version__

'1.6.0'

In [14]:
from __future__ import print_function
import torch

In [15]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0469e-38, 1.0194e-38, 9.2755e-39],
        [1.0194e-38, 9.8266e-39, 5.5103e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [4.1328e-39, 1.0102e-38, 1.0745e-38],
        [4.1328e-39, 4.5918e-39, 9.3673e-39]])


In [16]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7775, 0.7015, 0.6465],
        [0.5194, 0.8783, 0.4816],
        [0.6747, 0.5926, 0.0831],
        [0.1925, 0.0334, 0.2327],
        [0.4623, 0.3550, 0.4174]])


In [17]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [18]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [19]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [20]:
import torch
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [21]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.4277, -0.0071, -1.1457],
        [-1.3364, -1.6110, -0.7844],
        [-0.5673,  0.7641,  1.1532],
        [-0.6240, -1.3203, -0.4863],
        [ 0.9591,  0.8328, -1.4410]])


In [22]:
# 獲取size
print(x.size())
torch.Size([5,3])

torch.Size([5, 3])


torch.Size([5, 3])

In [23]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.1408,  0.9521, -0.2022],
        [-1.1121, -1.3253, -0.0607],
        [-0.3489,  1.0164,  2.0817],
        [-0.6174, -0.4572,  0.3826],
        [ 1.6228,  0.8420, -1.2284]])


In [24]:
# 加法2
print(torch.add(x,y))

tensor([[-0.1408,  0.9521, -0.2022],
        [-1.1121, -1.3253, -0.0607],
        [-0.3489,  1.0164,  2.0817],
        [-0.6174, -0.4572,  0.3826],
        [ 1.6228,  0.8420, -1.2284]])


In [25]:
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[-0.1408,  0.9521, -0.2022],
        [-1.1121, -1.3253, -0.0607],
        [-0.3489,  1.0164,  2.0817],
        [-0.6174, -0.4572,  0.3826],
        [ 1.6228,  0.8420, -1.2284]])


In [26]:
# 替換, adds x to y
y.add_(x)
print(y)

tensor([[-0.1408,  0.9521, -0.2022],
        [-1.1121, -1.3253, -0.0607],
        [-0.3489,  1.0164,  2.0817],
        [-0.6174, -0.4572,  0.3826],
        [ 1.6228,  0.8420, -1.2284]])


In [27]:
print(x[:, 1])

tensor([-0.0071, -1.6110,  0.7641, -1.3203,  0.8328])


In [28]:
# torch.view与Numpy的reshape类似
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # size -1 從其他維度推斷
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [29]:
# 如果你有只有一个元素的张量，使用.item()来得到Python数据类型的数值
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5416])
-0.5416328310966492


将Torch Tensor转换成NumPy array，反之亦然，这是轻而易举的。 Torch Tensor和NumPy array将共享它们的底层内存位置，更改其中一个将更改另一个。 将Torch Tensor转换为NumPy array。

In [30]:
import torch
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [32]:
# see how the numpy array changed in value
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### NumPy Array 转化成 Torch Tensor

In [33]:
# 使用from_numpy自動轉化
import numpy as np
a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到 NumPy 的转换.

In [34]:
# CUDA 张量. 使用.to 方法 可以将Tensor移动到任何设备中

# is_available 函數判斷是否有cuda可以使用
# ``torch.device`` 將張量移動到指定的設備中
if torch.cuda.is_available():
    device = torch.device("cuda") # a CUDA 設備對象
    y = torch.ones_like(x, device=device) # 直接從GPU創建張量 
    x = x.to(device) #或者直接使用``.to("cuda")``將張量移動到CUDA中
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))  # ``.TO``也會對變量的類型做更改

tensor([0.4584], device='cuda:0')
tensor([0.4584], dtype=torch.float64)


自动求导

In [35]:
%matplotlib inline

In [36]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [37]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [38]:
print(y.grad_fn)

In [39]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [42]:
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
print(a.grad_fn)

a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
None
True


In [43]:
out.backward()

In [44]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [45]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([ -300.6859,   531.6968, -1163.5959], grad_fn=<MulBackward0>)


In [46]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [47]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


神经网络

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Nodule):
    def __init__(self):
        