reference: https://zhuanlan.zhihu.com/p/101799677

In [15]:
import torch
torch.__version__

'1.6.0'

In [16]:
from __future__ import print_function
import torch

In [17]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [18]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9354, 0.0585, 0.2931],
        [0.5754, 0.6937, 0.6077],
        [0.3679, 0.2713, 0.1612],
        [0.9177, 0.6906, 0.1054],
        [0.5067, 0.2620, 0.7229]])


In [19]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [20]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [21]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [22]:
import torch
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [23]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.7275, -0.3024,  0.9671],
        [ 1.1751,  1.3361, -0.1158],
        [ 0.6181, -1.3421, -1.1144],
        [ 1.0632, -1.9091,  1.0249],
        [-0.0456,  1.7650,  0.2438]])


In [24]:
# 獲取size
print(x.size())
torch.Size([5,3])

torch.Size([5, 3])


torch.Size([5, 3])

In [25]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.0376,  0.6279,  1.6839],
        [ 1.9241,  2.3300, -0.0079],
        [ 1.5880, -0.6832, -0.2334],
        [ 1.3380, -1.2000,  1.5905],
        [ 0.6403,  2.4058,  0.3246]])


In [26]:
# 加法2
print(torch.add(x,y))

tensor([[-0.0376,  0.6279,  1.6839],
        [ 1.9241,  2.3300, -0.0079],
        [ 1.5880, -0.6832, -0.2334],
        [ 1.3380, -1.2000,  1.5905],
        [ 0.6403,  2.4058,  0.3246]])


In [27]:
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[-0.0376,  0.6279,  1.6839],
        [ 1.9241,  2.3300, -0.0079],
        [ 1.5880, -0.6832, -0.2334],
        [ 1.3380, -1.2000,  1.5905],
        [ 0.6403,  2.4058,  0.3246]])


In [28]:
# 替換, adds x to y
y.add_(x)
print(y)

tensor([[-0.0376,  0.6279,  1.6839],
        [ 1.9241,  2.3300, -0.0079],
        [ 1.5880, -0.6832, -0.2334],
        [ 1.3380, -1.2000,  1.5905],
        [ 0.6403,  2.4058,  0.3246]])


In [29]:
print(x[:, 1])

tensor([-0.3024,  1.3361, -1.3421, -1.9091,  1.7650])


In [30]:
# torch.view与Numpy的reshape类似
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # size -1 從其他維度推斷
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
